// Supported with union (c) 2018 Union team
// Add your sources this

// Automatically generated block
#pragma region Includes
#include "API_Implementation.cpp"
#include "Interchange.cpp"
#include "MyPrint.cpp"
#include "Spacer_Init.cpp"
#include "CSettings.cpp"
#include "zCSparseArray.cpp"
#include "KeysManager.cpp"
#include "Utils.cpp"
#include "PFXManager.cpp"
#include "Vob.cpp"
#include "Spacer_Hooks.cpp"
#include "Lists.cpp"
#include "TreeHierarchy.cpp"
#include "Trigger.cpp"
#include "CreateVobs.cpp"
#include "Waynet.cpp"
#include "NamesGenerator.cpp"
#include "CameraManager.cpp"
#include "Camera.cpp"
#include "Common.cpp"
#include "MultiSelect.cpp"
#include "VobManipulator.cpp"
#include "zCBinTree3DS.cpp"
#include "zProgMesh.cpp"
#include "Play.cpp"
#include "ItemsLocator.cpp"
#include "World.cpp"
#include "ActionRestore.cpp"
#include "Search.cpp"
#include "SpacerApp.cpp"
#include "Spacer_Loop.cpp"
#include "zCObjPresetLib.cpp"
#include "Export.cpp"
#include "MatTree.cpp"
#include "MatManager.cpp"
#include "GenerateVobsVisualsList.cpp"
#include "Plugin.cpp"
#pragma endregion

// ...