// Supported with union (c) 2018 Union team
// Add your sources this

// Automatically generated block
#pragma region Includes
#include "API_Implementation.cpp"
#include "Interchange.cpp"
#include "MyPrint.cpp"
#include "Spacer_Init.cpp"
#include "CSettings.cpp"
#include "KeysManager.cpp"
#include "Utils.cpp"
#include "PFXManager.cpp"
#include "Vob.cpp"
#include "Lists.cpp"
#include "TreeHierarchy.cpp"
#include "Trigger.cpp"
#include "CreateVobs.cpp"
#include "Waynet.cpp"
#include "NamesGenerator.cpp"
#include "CameraManager.cpp"
#include "Camera.cpp"
#include "Spacer_Hooks.cpp"
#include "MultiSelect.cpp"
#include "VobManipulator.cpp"
#include "BboxMovement.cpp"
#include "Play.cpp"
#include "ItemsLocator.cpp"
#include "PFX_Editor.cpp"
#include "World.cpp"
#include "ActionRestore.cpp"
#include "Search.cpp"
#include "SpacerApp.cpp"
#include "Spacer_Loop.cpp"
#include "GrassPlacer.cpp"
#include "Export.cpp"
#include "Export_Union_DLL.cpp"
#include "MatTree.cpp"
#include "MatManager.cpp"
#include "BboxDecalArea.cpp"
#include "AB_NoGrass_Init.cpp"
#include "GenerateVobsVisualsList.cpp"
#include "Macros.cpp"
#include "AB_NoGrass.cpp"
#include "MatFilter.cpp"
#include "MatFilter_LoadSave.cpp"
#include "ErrorReport.cpp"
#include "ErrorReport_Materials.cpp"
#include "AB_Debug.cpp"
#include "ErrorReport_Vobs.cpp"
#include "Load3DS_Fast.cpp"
#include "MatFilter_Render.cpp"
#include "TestLoop.cpp"
#include "zCObjPresetLib.cpp"
#include "Plugin.cpp"
#pragma endregion

// ...